In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('C:\\Users\\Sauraj (Work mode)\\Desktop\\temps.csv')
df

,year,month,day,week,temp_2,temp_1,average,actual,forecast_noaa,forecast_acc,forecast_under,friend
0,2016,1,1,Fri,45,45,45.6,45,43,50,44,29
1,2016,1,2,Sat,44,45,45.7,44,41,50,44,61
2,2016,1,3,Sun,45,44,45.8,41,43,46,47,56
3,2016,1,4,Mon,44,41,45.9,40,44,48,46,53
4,2016,1,5,Tues,41,40,46.0,44,46,46,46,41
5,2016,1,6,Wed,40,44,46.1,51,43,49,48,40
6,2016,1,7,Thurs,44,51,46.2,45,45,49,46,38
7,2016,1,8,Fri,51,45,46.3,48,43,47,46,34
8,2016,1,9,Sat,45,48,46.4,50,46,50,45,47
9,2016,1,10,Sun,48,50,46.5,52,45,48,48,49
10,2016,1,11,Mon,50,52,46.7,45,42,48,48,39
11,2016,1,12,Tues,52,45,46.8,49,44,50,45,61
12,2016,1,13,Wed,45,49,46.9,55,45,51,46,33
13,2016,1,14,Thurs,49,55,47.0,49,43,47,46,58
14,2016,1,15,Fri,55,49,47.1,48,46,51,46,65
15,2016,1,16,Sat,49,48,47.3,54,45,52,46,28
16,2016,1,17,Sun,48,54,47.4,50,45,51,46,47
17,2016,1,18,Mon,54,50,47.5,54,44,48,49,58
18,2016,1,19,Tues,50,54,47.6,48,47,49,48,53
19,2016,1,20,Wed,54,48,47.7,52,44,52,49,61
20,2016,1,21,Thurs,48,52,47.8,52,43,51,46,57
21,2016,1,22,Fri,52,52,47.9,57,47,48,48,60
22,2016,1,23,Sat,52,57,48.0,48,45,49,50,37
23,2016,1,24,Sun,57,48,48.1,51,46,50,48,54
24,2016,1,25,Mon,48,51,48.2,54,45,51,49,63
25,2016,1,26,Tues,51,54,48.3,56,44,53,50,61
26,2016,1,27,Wed,54,56,48.4,57,45,51,49,54
27,2016,1,28,Thurs,56,57,48.4,56,44,52,48,34
28,2016,1,29,Fri,57,56,48.5,52,48,52,47,49
29,2016,1,30,Sat,56,52,48.6,48,45,51,48,47
...,...,...,...,...,...,...,...,...,...,...,...,...
318,2016,12,2,Fri,52,46,47.2,50,46,51,49,41
319,2016,12,3,Sat,46,50,47.0,49,42,52,47,58
320,2016,12,4,Sun,50,49,46.8,46,45,47,47,53
321,2016,12,5,Mon,49,46,46.6,40,43,50,45,65
322,2016,12,6,Tues,46,40,46.4,42,44,50,45,56
323,2016,12,7,Wed,40,42,46.3,40,44,51,46,62
324,2016,12,8,Thurs,42,40,46.1,41,45,51,47,36
325,2016,12,9,Fri,40,41,46.0,36,43,51,44,54
326,2016,12,10,Sat,41,36,45.9,44,44,48,44,65
327,2016,12,11,Sun,36,44,45.7,44,41,46,47,35
328,2016,12,12,Mon,44,44,45.6,43,43,50,45,42
329,2016,12,13,Tues,44,43,45.5,40,41,47,46,46
330,2016,12,14,Wed,43,40,45.4,39,45,48,45,49
331,2016,12,15,Thurs,40,39,45.3,39,45,49,47,46
332,2016,12,16,Fri,39,39,45.3,35,44,49,44,39
333,2016,12,17,Sat,39,35,45.2,35,43,47,46,38
334,2016,12,18,Sun,35,35,45.2,39,44,46,46,36
335,2016,12,19,Mon,35,39,45.1,46,42,46,45,51
336,2016,12,20,Tues,39,46,45.1,51,45,49,45,62
337,2016,12,21,Wed,46,51,45.1,49,44,50,46,39
338,2016,12,22,Thurs,51,49,45.1,45,42,47,46,38
339,2016,12,23,Fri,49,45,45.1,40,45,49,44,35
340,2016,12,24,Sat,45,40,45.1,41,44,47,46,39
341,2016,12,25,Sun,40,41,45.1,42,42,49,44,31
342,2016,12,26,Mon,41,42,45.2,42,45,48,46,58
343,2016,12,27,Tues,42,42,45.2,47,41,50,47,47
344,2016,12,28,Wed,42,47,45.3,48,41,49,44,58
345,2016,12,29,Thurs,47,48,45.3,48,43,50,45,65
346,2016,12,30,Fri,48,48,45.4,57,44,46,44,42
347,2016,12,31,Sat,48,57,45.5,40,42,48,47,57

In [2]:
#Descriptive stats for each column
df.describe()

,year,month,day,temp_2,temp_1,average,actual,forecast_noaa,forecast_acc,forecast_under,friend
count,348.0,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000
mean,2016.0,6.477011,15.514368,62.652299,62.701149,59.760632,62.543103,57.238506,62.373563,59.772989,60.034483
std,0.0,3.498380,8.772982,12.165398,12.120542,10.527306,11.794146,10.605746,10.549381,10.705256,15.626179
min,2016.0,1.000000,1.000000,35.000000,35.000000,45.100000,35.000000,41.000000,46.000000,44.000000,28.000000
25%,2016.0,3.000000,8.000000,54.000000,54.000000,49.975000,54.000000,48.000000,53.000000,50.000000,47.750000
50%,2016.0,6.000000,15.000000,62.500000,62.500000,58.200000,62.500000,56.000000,61.000000,58.000000,60.000000
75%,2016.0,10.000000,23.000000,71.000000,71.000000,69.025000,71.000000,66.000000,72.000000,69.000000,71.000000
max,2016.0,12.000000,31.000000,117.000000,117.000000,77.400000,92.000000,77.000000,82.000000,79.000000,95.000000

In [2]:
#One-hot encoding the data using pandas to make the machine understand the data better
df = pd.get_dummies(df)
df.head()

,year,month,day,temp_2,temp_1,average,actual,forecast_noaa,forecast_acc,forecast_under,friend,week_Fri,week_Mon,week_Sat,week_Sun,week_Thurs,week_Tues,week_Wed
0,2016,1,1,45,45,45.6,45,43,50,44,29,1,0,0,0,0,0,0
1,2016,1,2,44,45,45.7,44,41,50,44,61,0,0,1,0,0,0,0
2,2016,1,3,45,44,45.8,41,43,46,47,56,0,0,0,1,0,0,0
3,2016,1,4,44,41,45.9,40,44,48,46,53,0,1,0,0,0,0,0
4,2016,1,5,41,40,46.0,44,46,46,46,41,0,0,0,0,0,1,0

In [3]:
#Labels are the values we want to predict
labels = np.array(df['actual'])

#Remove the labels from the dataframe and save it as a 'features' variable
features = df.drop('actual', axis = 1)

#Saving feature names for later usage
feature_list = list(features.columns)

#Conversion to array
features = np.array(features)

In [16]:
from sklearn.model_selection import train_test_split

#Splitting the data
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [17]:
print(train_labels.shape)

(261,)

In [18]:
#Creating a baseline to see if the model can outperform it

baseline_preds = test_features[:, feature_list.index('average')]

#Display baseline errors and display average baseline error
baseline_errors = abs(baseline_preds - test_labels)

print('Average baseline error is :', round(np.mean(baseline_errors), 2))

Average baseline error is : 5.06

In [19]:
#Model training
from sklearn.ensemble import RandomForestRegressor

#Instantiante the model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

#Train the model on the training data
rf.fit(train_features, train_labels)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [8]:
#Making predictions on the testing set
predictions = rf.predict(test_features)

#Calculating the error margin
errors = abs(predictions - test_labels)

print('Mean absoulte error of the model:', round(np.mean(errors), 2), 'degrees')

Mean absoulte error of the model: 3.87 degrees

In [9]:
#Determining performance metrics
mape = 100 * (errors / test_labels)

#Calculate and display accuracy
accuracy = 100 - np.mean(mape)
accuracy

93.93703038326089

In [25]:
#Variable importances
feature_importances = list(zip(feature_list, rf.feature_importances_))
#Call feature importances according to highest priority
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
feature_importances

[('temp_1', 0.6555532714734259),
 ('average', 0.15032982921113486),
 ('forecast_noaa', 0.04538229324882237),
 ('forecast_acc', 0.03485937239968537),
 ('forecast_under', 0.023190478556827154),
 ('day', 0.021119330680396457),
 ('temp_2', 0.020993283604658734),
 ('friend', 0.020684669325819475),
 ('month', 0.010329714202200238),
 ('week_Sat', 0.0036125047603753893),
 ('week_Fri', 0.003524921225987196),
 ('week_Mon', 0.0025881281964305544),
 ('week_Tues', 0.0023026580497519933),
 ('week_Sun', 0.0022890741053675184),
 ('week_Wed', 0.001974025572133548),
 ('week_Thurs', 0.0012664453869816017),
 ('year', 0.0)]

In [32]:
#Making a random forst with only the two most important variables, temp_1 and averge

rf_important = RandomForestRegressor(n_estimators = 1000, random_state = 42)

#Extraction of two most important features
imp_indices = [feature_list.index('temp_1'), feature_list.index('average')]
train_imp = train_features[:, imp_indices]
test_imp = test_features[:, imp_indices]

#Training the random forest
rf_important.fit(train_imp, train_labels)

#Making predictions to determine the error
predictions = rf_important.predict(test_imp)

errors = abs(predictions - test_labels)

#Displaying the performance metrics
print('MAE:', round(np.mean(errors), 2), 'degrees')

mape = np.mean(100 * (errors / test_labels))
accuracy = 100 - mape
accuracy

MAE: 3.91 degrees

93.78486525042076